builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -buildid= -X main.version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
upx:
  - enabled: true
    compress: best
    lzma: true
    goos:
      - linux

archives:
  - id: binary
    format: binary
  - id: compressed
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
