#!/usr/bin/env bash
set -e
fmt="$(gofmt -d ./)"
if [ $? -ne 0 ] || [ -n "$fmt" ]; then
    echo "$fmt" >&2
    exit 1
fi

vet="$(go vet ./)"
if [ $? -ne 0 ] || [ -n "$vet" ]; then
    echo "$vet" >&2
    exit 1
fi

go test
