#!/usr/bin/env bash
set -e
if ! [[ "$GITHUB_REF" == refs/tags/v* ]]; then
    echo "$GITHUB_REF is not a tagged version so aborting"
    exit 78
fi
tag="${GITHUB_REF##refs/tags/}"
export CGO_ENABLED=0
gox --output="builds/{{.Dir}}_{{.OS}}_{{.Arch}}" --ldflags="-X main.version=$tag"
ghr -soft -c "$GITHUB_SHA" "$tag" builds/
